version: '3.8'

services:
  web:
    build:
      context: .  # Specifies the context to use for building the image
      dockerfile: Dockerfile  # Specifies the Dockerfile to use
    ports:
      - "8080:80"  # Use this if port 80 is still busy
    volumes:
      - ./app:/app
    environment:
      FLASK_ENV: development
    working_dir: /app/app  # Set the working directory to the app folder
    command: ["gunicorn", "--bind", "0.0.0.0:80", "api:app"]  # Update to call app from api.py

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: rule_engine_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Megha*2904
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
