version: '3.8'  # Specify the Compose file version

services:
  web:
    build: .  # Use the Dockerfile in the current directory
    ports:
      - "8080:80"  # Map port 80 of the container to port 80 of the host
    volumes:
      - ./app:/app  # Mount the app directory to the container for live updates
    environment:
      FLASK_ENV: development  # Set Flask environment to development (optional)

  db:
    image: postgres:latest  # Use the official PostgreSQL image
    restart: always  # Always restart the database service
    environment:
      POSTGRES_DB: rule_engine_db  # Replace with your desired database name
      POSTGRES_USER: postgres  # Replace with your desired database user
      POSTGRES_PASSWORD: Megha*2904  # Replace with your desired password
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist database data

volumes:
  postgres_data:  # Define a volume for PostgreSQL data
